name = "Farmtech"
author = "jep"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de61a5109212c0c8a0dfff4f26b081d95b7e51bad98ece223b46d287aa1bb2d2"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
